# Generated by Django 5.2.1 on 2025-06-10 05:58

import store.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_orderitem_order_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/images/', validators=[store.validators.validate_file_size]),
        ),
    ]
